### ISSUE TITLE
Undefined name: ‘out’ in video2video.py

### ISSUE THREAD

**Issue by cclauss** [1991viet/ASCII-generator#2]
flake8 testing of https://github.com/1991viet/ASCII-generator on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./video2video.py:79:13: F821 undefined name 'out'
            out
            ^
1     F821 undefined name 'out'
1
```

**Comment by 1991viet** [comment]
Hi,
I haven't run it in python 3.7. But in version 2.7 or 3.6, my script works fine, since the first time variable "out" referred, an exception will be raised, then "out" will be initialized. After that, exception will never appear again.

**Comment by cclauss** [comment]
See #3
